# Generated by Django 2.2.7 on 2019-11-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('discounted_price', models.FloatField(blank=True)),
                ('image', models.TextField()),
                ('description', models.TextField()),
                ('slug', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
